package dev.sasikanth.twine.common.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_primary_20 = Color(0xFF442B00)
internal val md_theme_primary_80 = Color(0xFFFEBA4B)

internal val md_theme_error_20 = Color(0xFF690005)
internal val md_theme_error_80 = Color(0xFFFFB4AB)

internal val md_theme_light_primary = Color(0xFF835500)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFDDB5)
internal val md_theme_light_onPrimaryContainer = Color(0xFF2A1800)
internal val md_theme_light_secondary = Color(0xFF705B40)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFFBDEBC)
internal val md_theme_light_onSecondaryContainer = Color(0xFF271905)
internal val md_theme_light_tertiary = Color(0xFF52643F)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFD5EABA)
internal val md_theme_light_onTertiaryContainer = Color(0xFF111F03)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFBFF)
internal val md_theme_light_onBackground = Color(0xFF1F1B16)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF1F1B16)
internal val md_theme_light_surfaceVariant = Color(0xFFF0E0D0)
internal val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
internal val md_theme_light_outline = Color(0xFF817567)
internal val md_theme_light_outline_variant = Color(0x29835500)
internal val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
internal val md_theme_light_inverseSurface = Color(0xFF35302A)
internal val md_theme_light_inversePrimary = Color(0xFFFFB956)
internal val md_theme_light_surfaceTint = Color(0xFF835500)
internal val md_theme_light_scrim = Color(0x52000000)

internal val md_theme_dark_primary = Color(0xFFFFB956)
internal val md_theme_dark_onPrimary = Color(0xFF452B00)
internal val md_theme_dark_primaryContainer = Color(0xFF633F00)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB5)
internal val md_theme_dark_secondary = Color(0xFFDEC2A2)
internal val md_theme_dark_onSecondary = Color(0xFF3E2D16)
internal val md_theme_dark_secondaryContainer = Color(0xFF57432B)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
internal val md_theme_dark_tertiary = Color(0xFFB9CDA0)
internal val md_theme_dark_onTertiary = Color(0xFF253515)
internal val md_theme_dark_tertiaryContainer = Color(0xFF3B4C29)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFD5EABA)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1F1B16)
internal val md_theme_dark_onBackground = Color(0xFFEAE1D9)
internal val md_theme_dark_surface = Color(0xFF1F1B16)
internal val md_theme_dark_onSurface = Color(0xFFEAE1D9)
internal val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
internal val md_theme_dark_outline = Color(0xFF9C8F80)
internal val md_theme_dark_outline_variant = Color(0x29FFB956)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
internal val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
internal val md_theme_dark_inversePrimary = Color(0xFF835500)
internal val md_theme_dark_surfaceTint = Color(0xFFFFB956)
internal val md_theme_dark_scrim = Color(0xA3000000)
